config/routes.rb
Rails.application.routes.draw do

  devise_for :elko_users, {
    controllers: {
      sessions:      'elko_users/sessions',
      registrations: 'elko_users/registrations',
      invitations:   'elko_users/invitations',
      passwords:     'elko_users/passwords'
    },
    module: :devise
  }

  resources :elko_users, except: [:edit, :update] 
  namespace :elko do
    
    resource  :site_info, only: [:edit, :update]
    root 'dashboard#index'
    get '/settings', to: 'dashboard#settings', as: 'settings'
  end
end

app/models/elko/application_record.rb
module Elko
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/elko/block.rb
module Elko
  class Block < ApplicationRecord
  end
end

app/models/elko/site_info.rb
module Elko
  class SiteInfo < ApplicationRecord
  
    has_one_attached :logo

  end
end

app/models/elko/user_block.rb
module Elko
  class UserBlock < ApplicationRecord
    belongs_to :user
    belongs_to :block
  end
end

app/models/elko_user.rb
class ElkoUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable,
          :trackable, :invitable

  validates_presence_of :email
  validate :password_not_needed, on: :create

  def password_not_needed

  end

  def fullname
    if self.first_name.present?
      if  self.last_name.present?
        "#{first_name} #{last_name}"
      else
        "#{first_name}"
      end
    else
      "#{email}"
    end
  end
end

app/controllers/elko/application_controller.rb
module Elko
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/controllers/elko/blocks_controller.rb
class Elko::BlocksController < ElkoController
  helper_method :block_model
  before_action :set_item_name, only: [:show, :index, :new, :edit]

  def index
    @items = block_model.all
  end

  def new
    @item = block_model.new
  end

  def create
    @item = block_model.new block_params

    if @item.save
      flash[:success] = "Successfully created #{block_model.to_s}"
      redirect_to action: "show", id: @item
    else
      flash[:danger] = @item.errors.full_messages.to_sentence
      redirect_to action: "index", controller: block_model.to_s.pluralize.underscore
    end
  end

  def edit
    @item = block_model.friendly.find(params[:id])
  end

  def update
    @item = block_model.friendly.find(params[:id])

    if @item.update block_params
      flash[:success] = "Successfully updated #{block_model.to_s}"
      redirect_to action: "show", id: @item
    else
      flash[:danger] = @item.errors.full_messages.to_sentence
      redirect_to action: "index", controller: block_model.to_s.pluralize.underscore
    end
  end

  def show
    @item = block_model.friendly.find(params[:id])
  end

  def destroy
    @item = block_model.friendly.find(params[:id])

    if @item.destroy
      flash[:success] = "Successfully deleted #{block_model.to_s}"
      redirect_to action: "index", controller: block_model.to_s.pluralize.underscore
    else
      flash[:danger] = @item.errors.full_messages.to_sentence
      redirect_to action: "index", controller: block_model.to_s.pluralize.underscore
    end
  end

  def toggle_status
    @item = block_model.friendly.find(params[:id])
    @item.toggle_status
    redirect_back(fallback_location: elko_root_path)
  end

  private
  def block_params 
    params.require("#{block_model.to_s.underscore}").permit!
  end

  def set_item_name
    @item_name = block_model.to_s
  end
end

app/controllers/elko/dashboard_controller.rb
class Elko::DashboardController < ElkoController

  def index
    @blocks = Elko::Block.all
  end

  def settings

  end

end

app/controllers/elko/site_infos_controller.rb
class Elko::SiteInfosController < ElkoController

  def edit
    @site_info = Elko::SiteInfo.first
  end

  def update
    @site_info = Elko::SiteInfo.first

    if @site_info.update site_info_params
      flash[:success] = 'Successfully updated your website information'
      redirect_to elko_root_path
    else
      flash[:danger] = @site_info.errors.full_messages.to_sentence
      render 'edit'
    end 
  end

  private
    def site_info_params
      params.require(:elko_site_info).permit!
    end

end

app/controllers/elko_controller.rb
class ElkoController < ApplicationController
  layout 'elko/application'
  before_action :authenticate_elko_user!

end

app/controllers/elko_users/invitations_controller.rb
class ElkoUsers::InvitationsController < Devise::InvitationsController

  layout :set_layout

  def edit
    super
  end

  def after_invite_path_for(resource)
    elko_users_path
  end

  def after_accept_path_for(resource)
    elko_root_path
  end

  private

  def set_layout
    if action_name == 'edit' 
      'elko/auth'
    else 
      'elko/application'
    end
  end

end

app/controllers/elko_users/passwords_controller.rb
class ElkoUsers::PasswordsController < Devise::PasswordsController
  layout 'elko/auth'

  def after_sending_reset_password_instructions_path_for(resource_name)
    new_elko_user_session
  end

end

app/controllers/elko_users/registrations_controller.rb
class ElkoUsers::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters

  def new
    flash[:danger] = 'You are unauthorized to perform that action'
    redirect_to root_path # root path will exist when a root application exists
  end

  def create
    flash[:danger] = 'You are unauthorized to perform that action'
    redirect_to root_path # root path will exist when a root application exists
  end

  def after_update_path_for(resource)
    elko_users_path
  end

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

end

app/controllers/elko_users/sessions_controller.rb
class ElkoUsers::SessionsController < Devise::SessionsController
  layout 'elko/auth'
end

app/controllers/elko_users_controller.rb
class ElkoUsersController < ElkoController

  def index
    @users = ElkoUser.all
  end

  def new
    @user = ElkoUser.new
  end

  def create
    @user = ElkoUser.new user_params
    @user.password = 'password'

    if @user.save
      flash[:success] = "Successfully added user to the Elko Engine"
      redirect_to elko_users_path
    else
      flash[:danger] = @user.errors.full_messages.to_sentence
      render :new
    end
  end

  def destroy
    @user = ElkoUser.find(params[:id])

    if @user.destroy
      flash[:success] = "Successfully deleted User"
      redirect_to elko_users_path
    else
      flash[:danger] = @user.errors.full_messages.to_sentence
      redirect_to elko_users_path
    end
  end

  private
  def user_params
    params.require(:elko_user).permit(:email, :first_name, :last_name, :password, :password_confirmation)
  end 

end

app/helpers/elko/application_helper.rb
module Elko
  module ApplicationHelper

    def insert_images(item, text)
      images = text.scan(/\[ Image \d+ [^.!?\s][^.!?]*(?:[.!?](?!['"]?\s|$)[^.!?]*)*[.!?]?['"]?(?=\s|$) \]/)
      modifedText = text
      newText = ''

      return text if images.count < 1

      images.each do |image| 
        id = image.match(/\d+/)
        alt = image.match(/(?<=')(.+)(?=')/)
        path = ''
        if (item.images.exists?(id.to_s))
          path = rails_blob_url(item.images.find(id.to_s))
        else 
          path = 'none'
        end
        modifedText = modifedText.gsub("[ Image #{id.to_s} '#{alt.to_s}' ]", "<div class='image-container'><img alt='#{ alt }' width='500' src='#{ path }'></img></div>")
        newText = modifedText
      end
      newText
    end

    def format(item, text)
      newText = insert_images(item, text)
      sanitize newText.gsub('h1', 'h2')
    end

  end
end

app/views/elko/blocks/edit.html.erb
<h2 class='float-left'>Edit</h2>

<div class='float-right'>
  <% if block_model::VIEWABLE %>
    <%= link_to fa_icon('eye', text: "View this #{@item_name.singularize.titleize}"), { action: :show, id: @item }, class: 'btn btn-primary' %>
  <% end %>
  <%= link_to fa_icon('eye', text: "View all #{@item_name.pluralize.titleize}"), {action: :index, controller: @item_name.pluralize.underscore}, class: 'btn btn-success btn-md' %>
</div>

<hr class='fix-float'>

<%= simple_form_for @item, url: {action: :update} do |f| %>

  <%= f.submit class: 'float-right mb-10 btn btn-md btn-primary' %>

  <%= render partial: 'form', locals: { f: f } %>

  <%= f.submit class: 'mb-10 btn btn-md btn-primary' %>

  <br>

  <p><%= link_to 'Back', :back %></p>

<% end %>

app/views/elko/blocks/index.html.erb
<h2 class='float-left'><%= @item_name.pluralize.titleize %></h2>

<div class='float-right'>
  <% if block_model::ADDABLE %>
    <%= link_to fa_icon('plus', text: "New #{@item_name.titleize}"), {action: :new, id: @item}, class: 'btn btn-md btn-success' %>
  <% end %>
</div>

<hr class='fix-float'>

<% if @items.present? %>
  <table class="table table-striped table-hover table-bordered">
    <thead>
      <tr>
        <th scope="col"><%= @item_name.pluralize.titleize %></th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><strong><%= truncate(item.label, length: 70) %></strong></td>
          <td>
            <% if block_model::VIEWABLE %>
              <%= link_to fa_icon('eye', text: 'View'), { action: :show, id: item }, class: 'btn btn-info btn-sm'%>
            <% end %>

            <% if block_model::EDITABLE %>
              <%= link_to fa_icon('edit', text: 'Edit'), { action: :edit, id: item }, class: 'btn btn-warning btn-sm'%>
            <% end %>

            <% if block_model::PUBLISHABLE %>
              <% if item.unpublished? %>
                <%= link_to fa_icon('edit', text: 'Publish'), { action: :toggle_status, id: item }, method: :post, class: 'btn btn-primary btn-sm' %>
              <% else %>
                <%= link_to fa_icon('edit', text: 'Unpublish'), { action: :toggle_status, id: item }, method: :post, class: 'btn btn-primary btn-sm' %>
              <% end %>
            <% end %>

            <% if block_model::DELETEABLE %>
              <%= link_to fa_icon('trash', text: 'Delete'), { action: :destroy, id: item }, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/elko/blocks/new.html.erb
<h2 class='float-left'>Create A New <%= @item_name %></h2>
<%= link_to fa_icon('eye', text: "View All #{@item_name.pluralize}"), { controller: "#{@item_name.pluralize.underscore}", action: "index" }, class: 'btn btn-md btn-success float-right'%>

<hr class='fix-float'>

<%= simple_form_for @item, url: {action: :create} do |f| %>

  <%= render partial: 'form', locals: { f: f } %>

  <%= f.submit class: 'mb-10 btn btn-md btn-primary' %>

<% end %>

<br>

<p><%= link_to 'Back', :back %></p>

app/views/elko/blocks/show.html.erb
<h2 class='float-left'><%= @item.class.to_s.titleize %></h2>

<div class='float-right'>
  <%= link_to fa_icon('eye', text: "View all #{@item_name.titleize.pluralize}"), {action: :index, controller: @item_name.pluralize.underscore}, class: 'btn btn-success btn-md' %>

  <% if block_model::EDITABLE %>
    <%= link_to fa_icon('edit', text: "Edit #{@item_name.titleize.singularize}"), {action: :edit, id: @item }, class: 'btn btn-success btn-md' %>
  <% end %>

  <% if block_model::DELETEABLE %>
    <%= link_to fa_icon('trash', text: "Delete #{@item_name.titleize.singularize}"), {action: "destroy", id: @item }, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-success btn-md' %>
  <% end %>

  <% if block_model::PUBLISHABLE %>
    <% if @item.unpublished? %>
      <%= link_to fa_icon('upload', text: "Publish #{@item_name.titleize.singularize}"), {action: :toggle_status }, data: { confirm: 'Are you sure?' }, method: :post, class: 'btn btn-success btn-md' %>
    <% else %>
      <%= link_to fa_icon('upload', text: "Unpublish #{@item_name.titleize.singularize}"), {action: :toggle_status }, data: { confirm: 'Are you sure?' }, method: :post, class: 'btn btn-success btn-md' %>
    <% end %>
  <% end %>
</div>

<hr class='fix-float'>

<%= render 'content' %>

app/views/elko/dashboard/index.html.erb
<h2>Dashboard</h2>
<hr> 
<div class='row'>
  <% @blocks.each do |block| %>
    <div class='col-md-3'>
      <div class="card text-white bg-<%= cycle('primary', 'success', 'warning', 'danger', 'info', 'dark') %> mb-3">
        <div class="card-header"><%= block.title %></div>
        <div class="card-body">
          <h5 class="card-title">
            <%= link_to "View #{block.title}", {controller: block.controller}, style: 'color:white;'%>
          </h5>
        </div>
      </div>
    </div>
  <% end %>  
</div>

app/views/elko/dashboard/settings.html.erb
<h2>Settings</h2>
<hr>
<p>Nothing here yet!</p>

app/views/elko/dashboard/shared/_footer.html.erb
<footer class="sticky-footer">
  <div class="container my-auto">
    <div class="copyright text-center my-auto">
      <span>Copyright © Elko <%= Time.now.year %></span>
    </div>
  </div>
</footer>

app/views/elko/dashboard/shared/_navbar.html.erb
<nav class="navbar navbar-expand navbar-light bg-light static-top">
  <%= link_to "Elko Engine", elko_root_path, class: 'navbar-brand'%>
  <%= content_tag(:a, fa_icon('bars'), id: 'sidebarToggle') %>

  <!-- Navbar -->
  <ul class="navbar-nav ml-auto mr-0 mr-md-3 my-2 my-md-0">
    <%# <li class="nav-item dropdown no-arrow mx-1">
      <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-bell fa-fw"></i>
        <span class="badge badge-danger">9+</span>
      </a>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
        <a class="dropdown-item" href="#">Action</a>
        <a class="dropdown-item" href="#">Another action</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="#">Something else here</a>
      </div>
    </li>
    <li class="nav-item dropdown no-arrow mx-1">
      <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-envelope fa-fw"></i>
        <span class="badge badge-danger">7</span>
      </a>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="messagesDropdown">
        <a class="dropdown-item" href="#">Action</a>
        <a class="dropdown-item" href="#">Another action</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="#">Something else here</a>
      </div>
    </li> %>
    <li class="nav-item dropdown no-arrow">
      <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-user-circle fa-fw"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
        <%= link_to 'Profile Settings', edit_elko_user_registration_path, class: 'dropdown-item' %>
        <%= link_to 'Settings', elko_settings_path, class: 'dropdown-item' %>
        <div class="dropdown-divider"></div>
        <%= link_to 'Logout', destroy_elko_user_session_path, method: :delete, class: 'dropdown-item' %>
      </div>
    </li>
  </ul>

</nav>

app/views/elko/dashboard/shared/_sidebar.html.erb
<ul class="sidebar navbar-nav toggled">
  <li class="nav-item active">
    <a class="nav-link" href="<%= elko_root_path %>">
      <i class="fas fa-fw fa-clipboard"></i>
      <span>Dashboard</span>
    </a>
  </li>
  <li class="nav-item active">
    <a class="nav-link" href="<%= elko_users_path %>">
      <i class="fas fa-fw fa-user"></i>
      <span>Elko Users</span>
    </a>
  </li>
  <li class="nav-item active">
    <a class="nav-link" href="<%= elko_settings_path %>">
      <i class="fas fa-fw fa-cogs"></i>
      <span>Settings</span>
    </a>
  </li>
  <li class="nav-item active">
    <a class="nav-link" href="<%= edit_elko_site_info_path %>">
      <i class="fas fa-fw fa-info"></i>
      <span>Site Info</span>
    </a>
  </li>
  <% if defined? root_path %>
    <li class="nav-item active">
      <a class="nav-link" href="<%= root_path %>">
        <i class="fas fa-fw fa-eye"></i>
        <span>View Website</span>
      </a>
    </li>
  <% end %>
</ul>

app/views/elko/site_infos/edit.html.erb
<h2>Meta Website Information</h2>

<hr>

<%= simple_form_for @site_info, url: elko_site_info_path do |f| %>

  <%= f.input :website_name,
    label: 'What is the name of your business/website?',
    placeholder: 'Enter name here' 
  %>

  <hr>

  <%= image_tag @site_info.logo, width: '150' if @site_info.logo.attached?%>
  <p></p>
  <%= f.input :logo, label: 'Do you have a logo? add or change it here.'%>

  <%= f.submit 'Update Website Information', class: 'btn btn-primary' %>

<% end %>

app/views/elko_users/edit.html.erb
<h2>Update Your Profile</h2>
<hr>

<%= simple_form_for @user, url: edit_elko_user(@user) do |f| %>

  <%= f.input :first_name %>

  <%= f.input :last_name %>

  <%= f.input :email %>

  <%= f.input :%>

<% end %>

app/views/elko_users/index.html.erb
<h2 class='float-left'>Users</h2>
<%= link_to fa_icon('plus', text: 'Add User'), new_elko_user_invitation_path, class: 'btn btn-success btn-md float-right'%>

<hr class='fix-float'>

<table class="table table-striped table-hover table-bordered">
  <thead>
    <tr>
      <th scope="col">First</th>
      <th scope="col">Last</th>
      <th scope="col">Email</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td>
          <%= link_to fa_icon('trash', text: 'Delete'), elko_user_path(user), method: :delete, class: 'btn btn-danger btn-sm', data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/elko_users/invitations/edit.html.erb
<h2><%= t 'devise.invitations.edit.header' %></h2>

<%= simple_form_for resource, as: resource_name, url: invitation_path(resource_name), html: { method: :put } do |f| %>
  <%= devise_error_messages! %>
  <%= f.hidden_field :invitation_token %>

  <%= f.input :password %>
  <%= f.input :password_confirmation %>

  <%= f.button :submit, t("devise.invitations.edit.submit_button") %>
<% end %>

app/views/elko_users/invitations/new.html.erb
<h2><%= t "devise.invitations.new.header" %></h2>

<%= simple_form_for resource, as: resource_name, url: invitation_path(resource_name), html: { method: :post} do |f| %>
  <%= devise_error_messages! %>

<% resource.class.invite_key_fields.each do |field| -%>
  <div class='form-group'>
    <%= f.input field, input_html: { class: 'form-control' }%>
  </div>
<% end -%>

<%= f.button :submit, t("devise.invitations.new.submit_button") %>
<% end %>

app/views/elko_users/new.html.erb
<h2>Create a new Elko User</h2>
<hr>

<%= simple_form_for @user, url: elko_users_path do |f| %>

  <%= f.input :email %>

  <%= f.submit class: 'btn btn-md btn-primary'%>

<% end %>

app/views/elko_users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/elko/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Elko</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="robots" content="noindex">
    <meta name="googlebot" content="noindex">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <%= stylesheet_link_tag    "elko/application", media: "all" %>
    <%= javascript_include_tag "elko/application" %>
  </head>
  <body class='body sidebar-toggled'>
    <%= render partial: 'elko/dashboard/shared/navbar' %>
    <div id='wrapper'>
      <%= render partial: 'elko/dashboard/shared/sidebar' %>
      <div id='content-wrapper'>
        <div class='container-fluid'>
        <%= render partial: 'shared/flash' %>
        <%= yield %>
        </div>
        <%= render partial: 'elko/dashboard/shared/footer' %>
      </div>
    </div>
    <a class="scroll-to-top rounded" href="#page-top"><i class="fas fa-angle-up"></i></a>
  </body>
</html>

app/views/layouts/elko/auth.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Elko Engine</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="robots" content="noindex">
    <meta name="googlebot" content="noindex">

    <%= stylesheet_link_tag    'elko/application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'elko/application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container'>
      <%= render partial: 'shared/flash' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %> alert-dismissible fade show" role="alert">
    <%= value %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>